language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: python3 Main.py
addons:
  postgresql: "11"
before_script:
  - export DATABASE_URL="postgres://postgres@localhost/DPSBot"
  - createdb -U postgres DPSBot
  - pg_restore -U postgres --dbname=DPSBot < ./db-dump/backup.dump
