language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: python3 Main.py -test
env: DB=postgres
services:
  - postgresql
before_script:
  - psql -c 'create database DPSBot;' -U postgres
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - coveralls
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
