language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: python3 Main.py
env: DB=postgres
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - export DATABASE_URL="postgres://postgres@localhost/DPSBot"
  - psql -c 'create database DPSBot;' -U postgres
  - pg_restore -U postgres --dbname=DPSBot < ./db-dump/backup.dump
