language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: python3 Main.py
addons:
  postgresql: "9.6.8"
before_script:
  - createdb -U postgres DPSBot
  - pg_restore -U postgres --dbname=DPSBot < ./db-dump/backup.dump
