language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: python3 Main.py
env: DB=postgres
secure: "UScev46OgWeFeLB5W1dHJcmVHVUwaCBijNEU/UZUCAunfL+8PniW8HjEyljhSy8zS1m7f4BE5ME6+uAR2HpAfYG6BCh0wbs7tSoUYFvWWqNSLOcseiXzjflLfsxcccHXS3uHieFyEvW7HP1nmSvpqcnpe8RgTpIoDQCJ7oEAX5oC+lAtU26U2eYzPMxugHXAXkdxeZbweIcr6Ykrz6NVwdvG8misqpsEoFzxKas6HhMw8AvxR5tAs8XbMIJyNp1z9S3YV9Q5WF9PdW9s6sK5Kdk33nmjYLbC64vJOcZpN3+nW5+mVUqQAEHY1T2TazbY8bytnvFpjoJlxatXD40mYImjSLAKQuKFPmu3vng+0jVXWJRjYsDoT8CtdVuP9RdngdI8arWdEWz3lTukoGE0+lA77zt8e6cfib18lML4xZ0BH8vwex0EMqEpYmdN6OF38dFVnp6mJMK6B/1ialfinSRPU3R5+kOc+vwj7gmA/FwnpJx4UDl3NnyysoxCDK2DtQjZ6CorlZCP6+7Ws1ZuDSmYpf65Q51WnZt0K29OoKw3BjZ+oXB3D2JiwC51LNCWIvovsLVvnqoL1lW3Tp+kEC7Sc2JPcTb8AyBwSZgjqbq0DgYFFRBTkhhjPZ8Y/IGV7vd3g3q2FzjK1JWb2ZDvB6zVkfwiKUecnT6b5CqK+xQ="
services:
  - postgresql
